<a href="https://colab.research.google.com/github/venkatnivasreddyk/machine-learning-porjects-by-me-/blob/main/satellite_ipynp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install patchify

In [ ]:
import os
import cv2
from PIL import Image
import numpy as np
from patchify import patchify
from sklearn.preprocessing import MinMaxScaler, StandardScaler

from matplotlib import pyplot as plt
import random

In [ ]:
minmaxscaler = MinMaxScaler()

In [ ]:
!ls -lah '/content/drive/MyDrive/Colab Notebooks/datasets/satellite/DubaiDataset'

ls: cannot access '/content/drive/MyDrive/Colab Notebooks/datasets/satellite/DubaiDataset': No such file or directory


In [ ]:
dataset_root_folder = '/content/drive/MyDrive/Colab Notebooks/datasets/satellite/'

In [ ]:
dataset_name = "DubaiDataset"

In [ ]:
for path, subdirs, files in os.walk(os.path.join(dataset_root_folder, dataset_name)):
  dir_name = path.split(os.path.sep)[-1]
  #print(dir_name)
  if dir_name == 'masks': # 'images
    images = os.listdir(path)
    print(path)
    #print(images)
    for i, image_name in enumerate(images):
      if (image_name.endswith('.png')): # '.jpg
        #print(image_name)
        a = True

In [ ]:
image_patch_size = 256

In [ ]:
image = cv2.imread(f'{dataset_root_folder}/{dataset_name}/Tile 2/images/image_part_001.jpg',1)

In [ ]:
import cv2
import os

dataset_root_folder = '/path/to/your/dataset' # Replace with the actual path to your dataset
dataset_name = "DubaiDataset"
image_patch_size = 256

# Construct the image path using os.path.join for platform compatibility
image_path = os.path.join(dataset_root_folder, dataset_name, 'Tile 2', 'images', 'image_part_001.jpg')

# Check if the file exists before attempting to load it
if os.path.exists(image_path):
  image = cv2.imread(image_path, 1)

  # Check if the image was loaded successfully
  if image is not None:
    print(image.shape)
  else:
    print(f"Error: Could not load image from {image_path}. Please check the file path and permissions.")
else:
  print(f"Error: Image file not found at {image_path}.")

Error: Image file not found at /path/to/your/dataset/DubaiDataset/Tile 2/images/image_part_001.jpg.


In [ ]:
!pip install patchify opencv-python
import cv2
import os
import numpy as np # Import numpy
from patchify import patchify

dataset_root_folder = '/path/to/your/dataset' # Replace with the actual path to your dataset
dataset_name = "DubaiDataset"
image_patch_size = 256

# Construct the image path using os.path.join for platform compatibility
image_path = os.path.join(dataset_root_folder, dataset_name, 'Tile 2', 'images', 'image_part_001.jpg')

# Check if the file exists before attempting to load it
if os.path.exists(image_path):
  image = cv2.imread(image_path, 1)

  # Check if the image was loaded successfully
  if image is not None:
    print(image.shape)

    # Convert the image to a NumPy array with the correct dtype if necessary
    image = np.array(image)  # or image = image.astype(np.uint8)

    image_patches = patchify(image, (image_patch_size, image_patch_size, 3), step=image_patch_size)

  else:
    print(f"Error: Could not load image from {image_path}. Please check the file path and permissions.")
else:
  print(f"Error: Image file not found at {image_path}.")

Error: Image file not found at /path/to/your/dataset/DubaiDataset/Tile 2/images/image_part_001.jpg.


In [ ]:
minmaxscaler = MinMaxScaler()

In [ ]:
!pip install patchify opencv-python
import cv2
import os
import numpy as np # Import numpy
from patchify import patchify
from sklearn.preprocessing import MinMaxScaler # Make sure MinMaxScaler is imported


dataset_root_folder = '/path/to/your/dataset' # Replace with the actual path to your dataset
dataset_name = "DubaiDataset"
image_patch_size = 256

# Construct the image path using os.path.join for platform compatibility
image_path = os.path.join(dataset_root_folder, dataset_name, 'Tile 2', 'images', 'image_part_001.jpg')

# Check if the file exists before attempting to load it
if os.path.exists(image_path):
  image = cv2.imread(image_path, 1)

  # Check if the image was loaded successfully
  if image is not None:
    print(image.shape)

    # Convert the image to a NumPy array with the correct dtype if necessary
    image = np.array(image)  # or image = image.astype(np.uint8)

    image_patches = patchify(image, (image_patch_size, image_patch_size, 3), step=image_patch_size)

    minmaxscaler = MinMaxScaler() # Initialize MinMaxScaler here
    image_x = image_patches[0,0,:,:]
    #MinMaxScaler
    image_y = minmaxscaler.fit_transform(image_x.reshape(-1, image_x.shape[-1])).reshape(image_x.shape) # Now use image_patches and minmaxscaler

  else:
    print(f"Error: Could not load image from {image_path}. Please check the file path and permissions.")
else:
  print(f"Error: Image file not found at {image_path}.")

Error: Image file not found at /path/to/your/dataset/DubaiDataset/Tile 2/images/image_part_001.jpg.


NameError: name 'image_y' is not defined

In [ ]:
print(type(image))

<class 'NoneType'>


AttributeError: 'NoneType' object has no attribute '__array_interface__'

In [ ]:
image.shape

AttributeError: 'NoneType' object has no attribute 'shape'

In [ ]:
(image.shape[0]//image_patch_size)*image_patch_size

AttributeError: 'NoneType' object has no attribute 'shape'

In [ ]:
image_dataset = []
mask_dataset = []

for image_type in ['images' , 'masks']:
  if image_type == 'images':
    image_extension = 'jpg'
  elif image_type == 'masks':
     image_extension = 'png'
  for tile_id in range(1,8):
    for image_id in range(1,20):
      image = cv2.imread(f'{dataset_root_folder}/{dataset_name}/Tile {tile_id}/{image_type}/image_part_00{image_id}.{image_extension}',1)
      if image is not None:
        if image_type == 'masks':
          image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
        #print(image.shape)
        size_x = (image.shape[1]//image_patch_size)*image_patch_size
        size_y = (image.shape[0]//image_patch_size)*image_patch_size
        #print("{} --- {} - {}".format(image.shape, size_x, size_y))
        image = Image.fromarray(image)
        image = image.crop((0,0, size_x, size_y))
        #print("({},  {})".format(image.size[0],image.size[1]))
        image = np.array(image)
        patched_images = patchify(image, (image_patch_size, image_patch_size, 3), step=image_patch_size)
        #print(len(patched_images))
        for i in range(patched_images.shape[0]):
          for j in range(patched_images.shape[1]):
            if image_type == 'images':
              individual_patched_image = patched_images[i,j,:,:]
              #print(individual_patched_image.shape)
              individual_patched_image = minmaxscaler.fit_transform(individual_patched_image.reshape(-1, individual_patched_image.shape[-1])).reshape(individual_patched_image.shape)
              individual_patched_image = individual_patched_image[0]
              #print(individual_patched_image.shape)
              image_dataset.append(individual_patched_image)
            elif image_type == 'masks':
              individual_patched_mask = patched_images[i,j,:,:]
              individual_patched_mask = individual_patched_mask[0]
              mask_dataset.append(individual_patched_mask)


In [ ]:
print(len(image_dataset))
print(len(mask_dataset))

0
0


In [ ]:
image_dataset = np.array(image_dataset)
mask_dataset = np.array(mask_dataset)

In [ ]:
print(len(image_dataset))
print(len(mask_dataset))

0
0


In [ ]:
import cv2
import numpy as np
from patchify import patchify
from PIL import Image
from sklearn.preprocessing import MinMaxScaler
import random
import matplotlib.pyplot as plt

# ... (Your existing code for dataset paths and patch size) ...

image_dataset = []
mask_dataset = []

for image_type in ['images', 'masks']:
    if image_type == 'images':
        image_extension = 'jpg'
    elif image_type == 'masks':
        image_extension = 'png'
    for tile_id in range(1, 8):
        for image_id in range(1, 20):
            # Construct the image path using f-string formatting
            image_path = f'{dataset_root_folder}/{dataset_name}/Tile {tile_id}/{image_type}/image_part_00{image_id}.{image_extension}'

            # Print the image path for debugging
            print(f"Loading image: {image_path}")

            # Load the image using cv2.imread
            image = cv2.imread(image_path, 1)

            # Check if the image was loaded successfully
            if image is not None:
                if image_type == 'masks':
                    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

                # ... (Rest of your image processing code) ...
            else:
                print(f"Failed to load image: {image_path}")

# ... (Rest of your code) ...

# Check if image_dataset is empty before selecting a random image
if len(image_dataset) > 0:
    random_image_id = random.randint(0, len(image_dataset) - 1)  # Subtract 1 to avoid index out of bounds

    plt.figure(figsize=(14, 8))
    plt.subplot(121)
    plt.imshow(image_dataset[random_image_id])
    plt.subplot(122)
    plt.imshow(mask_dataset[random_image_id])
    plt.show()
else:
    print("image_dataset is empty. No images to display.")

Loading image: /path/to/your/dataset/DubaiDataset/Tile 1/images/image_part_001.jpg
Failed to load image: /path/to/your/dataset/DubaiDataset/Tile 1/images/image_part_001.jpg
Loading image: /path/to/your/dataset/DubaiDataset/Tile 1/images/image_part_002.jpg
Failed to load image: /path/to/your/dataset/DubaiDataset/Tile 1/images/image_part_002.jpg
Loading image: /path/to/your/dataset/DubaiDataset/Tile 1/images/image_part_003.jpg
Failed to load image: /path/to/your/dataset/DubaiDataset/Tile 1/images/image_part_003.jpg
Loading image: /path/to/your/dataset/DubaiDataset/Tile 1/images/image_part_004.jpg
Failed to load image: /path/to/your/dataset/DubaiDataset/Tile 1/images/image_part_004.jpg
Loading image: /path/to/your/dataset/DubaiDataset/Tile 1/images/image_part_005.jpg
Failed to load image: /path/to/your/dataset/DubaiDataset/Tile 1/images/image_part_005.jpg
Loading image: /path/to/your/dataset/DubaiDataset/Tile 1/images/image_part_006.jpg
Failed to load image: /path/to/your/dataset/DubaiDat

In [ ]:
class_building = '#3C1098'
class_building = class_building.lstrip('#')
class_building = np.array(tuple(int(class_building[i:i+2], 16) for i in (0,2,4)))
print(class_building)

class_land = '#8429F6'
class_land = class_land.lstrip('#')
class_land = np.array(tuple(int(class_land[i:i+2], 16) for i in (0,2,4)))
print(class_land)

class_road = '#6EC1E4'
class_road = class_road.lstrip('#')
class_road = np.array(tuple(int(class_road[i:i+2], 16) for i in (0,2,4)))
print(class_road)

class_vegetation = '#FEDD3A'
class_vegetation = class_vegetation.lstrip('#')
class_vegetation = np.array(tuple(int(class_vegetation[i:i+2], 16) for i in (0,2,4)))
print(class_vegetation)

class_water = '#E2A929'
class_water = class_water.lstrip('#')
class_water = np.array(tuple(int(class_water[i:i+2], 16) for i in (0,2,4)))
print(class_water)

class_unlabeled = '#9B9B9B'
class_unlabeled = class_unlabeled.lstrip('#')
class_unlabeled = np.array(tuple(int(class_unlabeled[i:i+2], 16) for i in (0,2,4)))
print(class_unlabeled)

[ 60  16 152]
[132  41 246]
[110 193 228]
[254 221  58]
[226 169  41]
[155 155 155]


In [ ]:
import cv2
import numpy as np
from patchify import patchify
from PIL import Image
from sklearn.preprocessing import MinMaxScaler
import random
import matplotlib.pyplot as plt

# ... (Your existing code for dataset paths and patch size) ...

image_dataset = []
mask_dataset = []

for image_type in ['images', 'masks']:
    if image_type == 'images':
        image_extension = 'jpg'
    elif image_type == 'masks':
        image_extension = 'png'
    for tile_id in range(1, 8):
        for image_id in range(1, 20):
            # Construct the image path using f-string formatting
            image_path = f'{dataset_root_folder}/{dataset_name}/Tile {tile_id}/{image_type}/image_part_00{image_id}.{image_extension}'

            # Print the image path for debugging
            print(f"Loading image: {image_path}")

            # Load the image using cv2.imread
            image = cv2.imread(image_path, 1)

            # Check if the image was loaded successfully
            if image is not None:
                if image_type == 'masks':
                    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

                # Append the image to the appropriate dataset
                if image_type == 'images':
                    image_dataset.append(image)
                elif image_type == 'masks':
                    mask_dataset.append(image)
            else:
                print(f"Failed to load image: {image_path}")

# Convert the lists to NumPy arrays
image_dataset = np.array(image_dataset)
mask_dataset = np.array(mask_dataset)

# ... (Rest of your code) ...

# Check if image_dataset is empty before selecting a random image
if len(image_dataset) > 0:
    random_image_id = random.randint(0, len(image_dataset) - 1)  # Subtract 1 to avoid index out of bounds

    plt.figure(figsize=(14, 8))
    plt.subplot(121)
    plt.imshow(image_dataset[random_image_id])
    plt.subplot(122)
    plt.imshow(mask_dataset[random_image_id])
    plt.show()
else:
    print("image_dataset is empty. No images to display.")

Loading image: /path/to/your/dataset/DubaiDataset/Tile 1/images/image_part_001.jpg
Failed to load image: /path/to/your/dataset/DubaiDataset/Tile 1/images/image_part_001.jpg
Loading image: /path/to/your/dataset/DubaiDataset/Tile 1/images/image_part_002.jpg
Failed to load image: /path/to/your/dataset/DubaiDataset/Tile 1/images/image_part_002.jpg
Loading image: /path/to/your/dataset/DubaiDataset/Tile 1/images/image_part_003.jpg
Failed to load image: /path/to/your/dataset/DubaiDataset/Tile 1/images/image_part_003.jpg
Loading image: /path/to/your/dataset/DubaiDataset/Tile 1/images/image_part_004.jpg
Failed to load image: /path/to/your/dataset/DubaiDataset/Tile 1/images/image_part_004.jpg
Loading image: /path/to/your/dataset/DubaiDataset/Tile 1/images/image_part_005.jpg
Failed to load image: /path/to/your/dataset/DubaiDataset/Tile 1/images/image_part_005.jpg
Loading image: /path/to/your/dataset/DubaiDataset/Tile 1/images/image_part_006.jpg
Failed to load image: /path/to/your/dataset/DubaiDat

In [ ]:
label = individual_patched_mask

In [ ]:
def rgb_to_label(label):
  label_segment = np.zeros(label.shape, dtype=np.uint8)
  label_segment[np.all(label == class_water, axis=-1)] = 0
  label_segment[np.all(label == class_land, axis=-1)] = 1
  label_segment[np.all(label == class_road, axis=-1)] = 2
  label_segment[np.all(label == class_building, axis=-1)] = 3
  label_segment[np.all(label == class_vegetation, axis=-1)] = 4
  label_segment[np.all(label == class_unlabeled, axis=-1)] = 5
  #print(label_segment)
  label_segment = label_segment[:,:,0]
  #print(label_segment)
  return label_segment

In [ ]:
labels = []
for i in range(mask_dataset.shape[0]):
  label = rgb_to_label(mask_dataset[i])
  labels.append(label)

In [ ]:
print(len(labels))

0


In [ ]:
labels = np.array(labels)

In [ ]:
labels = np.expand_dims(labels, axis=-1)

In [ ]:
np.unique(labels)

array([], dtype=float64)

In [ ]:
print("Total unique labels based on masks: ",format(np.unique(labels)))

Total unique labels based on masks:  []


In [ ]:
labels[0][:,:,0]

IndexError: index 0 is out of bounds for axis 0 with size 0

In [ ]:
total_classes = len(np.unique(labels))

In [ ]:
total_classes

0

In [ ]:
from tensorflow.keras.utils import to_categorical

In [ ]:
import numpy as np
from tensorflow.keras.utils import to_categorical

# ... (Your existing code to load and preprocess labels) ...

# Ensure labels is not empty and has at least one unique value
# For example, if 'labels' is a 3D array:
if labels.size == 0 or len(np.unique(labels)) == 0:
    # Handle the empty or no unique label case
    # You might need to raise an exception, assign a default value, or skip this sample
    # Example for assigning a default value of 1 class
    total_classes = 1
else:
    total_classes = len(np.unique(labels))  # Determine the number of classes if not empty

# Proceed with one-hot encoding
labels_categorical_dataset = to_categorical(labels, num_classes=total_classes)

In [ ]:
labels_categorical_dataset.shape

(0, 1)

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
# Assuming your dataset is in a file named 'my_dataset.npy'
import numpy as np

master_training_dataset = np.load('my_dataset.npy')

   # or if it's a pandas DataFrame
import pandas as pd
master_training_dataset = pd.read_csv('my_dataset.csv')

   # ... (rest of your code) ...

FileNotFoundError: [Errno 2] No such file or directory: 'my_dataset.npy'

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(master_trianing_dataset, labels_categorical_dataset, test_size=0.15, random_state=100)

NameError: name 'master_trianing_dataset' is not defined

In [ ]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

In [ ]:
image_height = X_train.shape[1]
image_width = X_train.shape[2]
image_channels = X_train.shape[3]
total_classes = y_train.shape[3]

In [ ]:
print(image_height)
print(image_width)
print(image_channels)
print(total_classes)